slack:
  enabled: False
  webhook_url: "https://hooks.slack.com/services/XXXXXXXX"

logging:
  level: INFO
  format: '[%(asctime)-15s] %(message)s'

crawler:
  icebreaker-mens:
    url: 'https://www.icebreaker.com/en-us/web-specials?prefn1=gender&prefn2=phClass&prefv3=S&prefv1=Mens&prefv2=Short%20Sleeve%20Tops&prefn3=size&format=ajax'
  patagonia:
    urls:
      - "https://www.patagonia.com/shop/web-specials-mens?prefn1=size&sz={window_size}&start={start_pos}&format=page-element&prefv1=XS"
      - "https://www.patagonia.com/shop/web-specials-kids-boys?prefn1=size&sz={window_size}&start={start_pos}&format=page-element&prefv1=XXL"
      - "https://www.patagonia.com/shop/web-specials-womens?prefn1=size&sz={window_size}&start={start_pos}&format=page-element&prefv1=S%7CXS"
    params:
      window_size: 36
      total_limit: 200
    blacklist:
      - 'Responsibili-Tee'
      - 'T-Shirt'
      - 'Boxers'
      - 'Pants'
      - 'Waders'
